/*//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : AccesoPuerta
//PROCESO : Juego
//DESCRIPCION : El codigo presentara el gif de Alí Babá al ingreso de la cueva y el audio del juego
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 
*/
package Ventanas;

import com.sun.awt.AWTUtilities;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

public class AccesoPuerta extends javax.swing.JFrame implements ActionListener {

    double i = 50, j = 1;
    static Timer t = null;

    public static int prueba3 = 0;

    AudioClip sonar;

    public AccesoPuerta() {
        initComponents();
        btn_skip.setOpaque(false);
        btn_skip.setBorder(BorderFactory.createEmptyBorder());
        btn_skip.setContentAreaFilled(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        t = new Timer(8000, this);
        t.start();
        musica();
        ((JPanel) getContentPane()).setOpaque(false);

        AWTUtilities.setWindowOpaque(this, false);
    }

    public void musica() {
        sonar = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/abrir.wav"));
        sonar.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_skip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_skip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_skip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/skip.png"))); // NOI18N
        btn_skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skipMouseClicked(evt);
            }
        });
        btn_skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_skipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abretesesamo.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 630, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pergamino3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 340, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondow.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_skipActionPerformed
       
    }//GEN-LAST:event_btn_skipActionPerformed

    private void btn_skipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skipMouseClicked
         AccesoCueva ve = new AccesoCueva();
        ve.setVisible(true);
        sonar.stop();
        t.stop();
        this.dispose();
    }//GEN-LAST:event_btn_skipMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoPuerta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_skip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
  @Override
    public void actionPerformed(ActionEvent e) {

        if (prueba3 == 0) {
            if (e.getSource() == t && prueba3 == 0) {
                prueba3++;
                //llamar a la nueva ventana aqui
                AccesoCueva v = new AccesoCueva();
                v.setVisible(true);
                this.dispose();
                sonar.stop();
                t.stop();
                t=null;
            }
        }
    }

    public static Timer getT() {
        return t;
    }

    public static void setT(Timer t) {
        AccesoPuerta.t = t;
    }

    public static int getPrueba3() {
        return prueba3;
    }

    public static void setPrueba3(int prueba3) {
        AccesoPuerta.prueba3 = prueba3;
    }

}
