/*
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : Historia
//PROCESO : Introducción 
//DESCRIPCION : El código indicara el gift de Alí Babá con su audio 
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.Timer;


public class Historia extends javax.swing.JFrame implements ActionListener {

    static Timer t=null;

    public static Timer getT() {
        return t;
    }

    public static void setT(Timer t) {
        Historia.t = t;
    }
    
    AudioClip sonar;
    public static int prueba1 = 0;

    public Historia() {
        initComponents();
        btn_skip.setOpaque(false);
        btn_skip.setBorder(BorderFactory.createEmptyBorder());
        btn_skip.setContentAreaFilled(false);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        
        t = new Timer(30150, this);
        t.start();
        musica();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_skip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_skip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_skip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/skip.png"))); // NOI18N
        btn_skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_skipMouseClicked(evt);
            }
        });
        btn_skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_skipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/introduccion.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondow.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_skipActionPerformed
      
    }//GEN-LAST:event_btn_skipActionPerformed

    private void btn_skipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_skipMouseClicked
          PalabraSecreta ve = new PalabraSecreta();
        ve.setVisible(true);
        sonar.stop();
        t.stop();
        this.dispose();

    }//GEN-LAST:event_btn_skipMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_skip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

        if (prueba1 == 0) {
            if (e.getSource() == t && prueba1 == 0) {
//                dispose();
                prueba1++;

                PalabraSecreta s = new PalabraSecreta();
                s.setVisible(true);
                this.dispose();
                t.stop();
                t=null;
            }
        }
    }

    public void musica() {
        sonar = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/introduccion.wav"));
        sonar.play();
    }
     public static int getPrueba1() {
        return prueba1;
    }

    public static void setPrueba1(int prueba1) {
        Historia.prueba1 = prueba1;
    }

}
