/*
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : InicioSesion
//PROCESO : Ingreso
//DESCRIPCION : El código está validado para el ingreso del jugador 
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import Clases.Archivo;
import Clases.Jugador;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class IniciarSesion extends javax.swing.JFrame {

    static int contador = 3;

    public static ArrayList<Jugador> listaJugadores = new ArrayList<>();

    static Archivo archivo = new Archivo();
    static Jugador jugador, lista[];
    public static String ganadas;
    public static String jugadas;
    public static String perdidas;
    public static double record;
    public static String nombres = "";
    public static int posicion = 0;
    public static int contpos = 0;

    public IniciarSesion() {

        initComponents();

        try {
            archivo.listar("C:/AliBabá/Jugadores.txt", listaJugadores);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }

        setLocationRelativeTo(this);

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new jtextfieldround.JTextFieldRound();
        txt_contrasena = new jtextfieldround.JPasswordFieldRound();
        jLabel7 = new javax.swing.JLabel();
        btn_registrarse = new javax.swing.JButton();
        btn_iniciarSesion = new javax.swing.JButton();
        avatarOriginal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 530));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_usuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_usuario.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        txt_usuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 30));
        getContentPane().add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 200, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel7.setText("¿Aún no tienes una cuenta?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 310, 30));

        btn_registrarse.setFont(new java.awt.Font("Lucida Handwriting", 0, 16)); // NOI18N
        btn_registrarse.setText("Regístrate");
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        btn_iniciarSesion.setFont(new java.awt.Font("Lucida Handwriting", 0, 16)); // NOI18N
        btn_iniciarSesion.setText("Iniciar sesión");
        btn_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        avatarOriginal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musulman.png"))); // NOI18N
        getContentPane().add(avatarOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, 200));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 790, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIA SESIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, 970, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoArabew.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REGISTRARSE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 20, 970, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarSesionActionPerformed
        String direccion = "C:/AliBabá/Jugadores.txt";
        Archivo archivito = new Archivo();

        if (archivo.archivoExiste(direccion)) {
            Icon a = new ImageIcon(getClass().getResource("/imagenes/enojado.png"));
            
            try {
                if (txt_usuario.getText() == null || txt_usuario.getText().equals("") || txt_contrasena.getText() == null || txt_contrasena.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Asegúrate de llenar todos los campos ", "ERROR", JOptionPane.CANCEL_OPTION, a);
                    return;
                }

                if (buscarJugador(txt_usuario.getText()) == false || buscarContrasena(txt_contrasena.getText()) == false) {
                    contador--;
                    validar();

                } else {

                    IntermediaSplash bi = new IntermediaSplash();
                    bi.setVisible(true);
                    this.dispose();

                }
                

                ganadas = String.valueOf(listaJugadores.get(posicion).getGanadas());
                jugadas = String.valueOf(listaJugadores.get(posicion).getJugadas());
                perdidas = String.valueOf(listaJugadores.get(posicion).getPerdidas());
                record = listaJugadores.get(posicion).getRecord();
                nombres = txt_usuario.getText();
             

            } catch (HeadlessException | IOException | ClassNotFoundException i) {
            }
        }else{
                JOptionPane.showMessageDialog(null, "No existen usuarios registrados, por favor registrese primero", "ERROR", JOptionPane.CANCEL_OPTION, d);
                Registro r = new Registro();
                r.setVisible(true);
                this.dispose();
            }
        
    }//GEN-LAST:event_btn_iniciarSesionActionPerformed

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        Registro p = new Registro();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarOriginal;
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private jtextfieldround.JPasswordFieldRound txt_contrasena;
    private jtextfieldround.JTextFieldRound txt_usuario;
    // End of variables declaration//GEN-END:variables

    public static boolean buscarJugador(String nombre) throws IOException, FileNotFoundException, ClassNotFoundException {
        Jugador ju = null;
        posicion = 0;
        contpos = 0;
        boolean existe = false;
        for (Jugador p : listaJugadores) {
            if (p.getNombre().equals(nombre)) {
                ju = p;
                existe = true;
                posicion = contpos;
            }
            contpos++;
        }

        return existe;
    }

    public static boolean buscarContrasena(String contrasena) throws IOException, FileNotFoundException, ClassNotFoundException {
        Jugador co = null;
        boolean existe = false;
        for (Jugador p : listaJugadores) {
            if (p.getContrasena().equals(contrasena)) {
                co = p;
                existe = true;
            }
        }
        return existe;
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/0intentos.png"));
    Icon n = new ImageIcon(getClass().getResource("/imagenes/1intentos.png"));
    Icon d = new ImageIcon(getClass().getResource("/imagenes/2intentos.png"));
    Icon e = new ImageIcon(getClass().getResource("/imagenes/enojado.png"));

    public void validar() {
        posicion = 0;
        contpos = 0;
        switch (contador) {

            case 2:
                JOptionPane.showMessageDialog(null, " Nombre de usuario o contraseña incorrectos, tienes " + (contador) + " intentos", "Error de inicio de sesión", JOptionPane.CANCEL_OPTION, d);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, " Nombre de usuario o contraseña incorrectos, tienes " + (contador) + " intentos", "Error de inicio de sesión", JOptionPane.CANCEL_OPTION, n);
                break;
            case 0:

                JOptionPane.showMessageDialog(null, "Oh no! Se te han acabado los intentos", "SIN INTENTOS", JOptionPane.CANCEL_OPTION, e);

                System.exit(0);

                contador = 3;
                Historia.setPrueba1(0);
                Genio.setPrueba2(0);
                break;
            default:
                break;
        }

    }
}
