/*
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : PalabraSecreta
//PROCESO : Juego 
//DESCRIPCION : El coódigo esta validad para que el jugador escoja la palabra correcta
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import Clases.Pregunta;
import com.sun.awt.AWTUtilities;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class PalabraSecreta extends javax.swing.JFrame {

    static int contador = 3;

    public PalabraSecreta() {
        initComponents();

        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        btn_lampara2.setOpaque(false);
        btn_lampara2.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara2.setContentAreaFilled(false);
        btn_lampara2.setToolTipText("avatud");
        btn_lampara10.setOpaque(false);
        btn_lampara10.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara10.setContentAreaFilled(false);
        btn_lampara10.setToolTipText("abrir por favor");
        btn_lampar9.setOpaque(false);
        btn_lampar9.setBorder(BorderFactory.createEmptyBorder());
        btn_lampar9.setContentAreaFilled(false);
        btn_lampar9.setToolTipText("alohomora");
        btn_lampara8.setOpaque(false);
        btn_lampara8.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara8.setContentAreaFilled(false);
        btn_lampara8.setToolTipText("odprto");
        btn_lampara7.setOpaque(false);
        btn_lampara7.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara7.setContentAreaFilled(false);
        btn_lampara7.setToolTipText("atviras");
        btn_lampara.setOpaque(false);
        btn_lampara.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara.setContentAreaFilled(false);
        btn_lampara.setToolTipText("abrir");
        btn_lampara6.setOpaque(false);
        btn_lampara6.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara6.setContentAreaFilled(false);
        btn_lampara6.setToolTipText("ábrete Sésamo");
        btn_lampara5.setOpaque(false);
        btn_lampara5.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara5.setContentAreaFilled(false);
        btn_lampara5.setToolTipText("aperto");
        btn_lampara4.setOpaque(false);
        btn_lampara4.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara4.setContentAreaFilled(false);
        btn_lampara4.setToolTipText("buka");
        btn_lampara3.setOpaque(false);
        btn_lampara3.setBorder(BorderFactory.createEmptyBorder());
        btn_lampara3.setContentAreaFilled(false);
        btn_lampara3.setToolTipText("ouvert");

        btn_genio.setOpaque(false);
        btn_genio.setBorder(BorderFactory.createEmptyBorder());
        btn_genio.setContentAreaFilled(false);
        btn_genio.setToolTipText("Pista");
        btn_regresar.setOpaque(false);
        btn_regresar.setOpaque(false);
        btn_regresar.setBorder(BorderFactory.createEmptyBorder());
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setToolTipText("regresar");
        ((JPanel) getContentPane()).setOpaque(false);

        AWTUtilities.setWindowOpaque(this, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_lampara = new javax.swing.JButton();
        btn_lampara2 = new javax.swing.JButton();
        btn_genio = new javax.swing.JButton();
        btn_lampara3 = new javax.swing.JButton();
        btn_lampara4 = new javax.swing.JButton();
        btn_lampara5 = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        btn_lampara6 = new javax.swing.JButton();
        btn_lampara7 = new javax.swing.JButton();
        btn_lampara8 = new javax.swing.JButton();
        btn_lampar9 = new javax.swing.JButton();
        btn_lampara10 = new javax.swing.JButton();
        lbl_texto = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 507));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_lampara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara.setBorder(null);
        btn_lampara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamparaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 130, 100));

        btn_lampara2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara2.setBorder(null);
        btn_lampara2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 100));

        btn_genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pista2.gif"))); // NOI18N
        btn_genio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_genioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 120, 310));

        btn_lampara3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara3.setBorder(null);
        btn_lampara3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lampara3MouseClicked(evt);
            }
        });
        btn_lampara3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 130, 100));

        btn_lampara4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara4.setBorder(null);
        btn_lampara4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, 100));

        btn_lampara5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara5.setBorder(null);
        btn_lampara5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 130, 100));

        btn_regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, 60));

        btn_lampara6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara6.setBorder(null);
        btn_lampara6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lampara6MouseClicked(evt);
            }
        });
        btn_lampara6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 130, 100));

        btn_lampara7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara7.setBorder(null);
        btn_lampara7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        btn_lampara8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara8.setBorder(null);
        btn_lampara8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, 100));

        btn_lampar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampar9.setBorder(null);
        btn_lampar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampar9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 100));

        btn_lampara10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lampAn.gif"))); // NOI18N
        btn_lampara10.setBorder(null);
        btn_lampara10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lampara10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lampara10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 130, 100));

        lbl_texto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/frase.png"))); // NOI18N
        getContentPane().add(lbl_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Palabraw.png"))); // NOI18N
        lbl_fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fondoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_lampara2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara2ActionPerformed

        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();

    }//GEN-LAST:event_btn_lampara2ActionPerformed

    private void btn_lampara8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara8ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara8ActionPerformed

    private void btn_lampara7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara7ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara7ActionPerformed

    private void btn_lamparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamparaActionPerformed

        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", null, JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lamparaActionPerformed

    private void btn_lampara6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara6ActionPerformed

        AccesoPuerta p = new AccesoPuerta();
        p.setVisible(true);
        this.hide();

    }//GEN-LAST:event_btn_lampara6ActionPerformed

    private void btn_lampara5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara5ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara5ActionPerformed

    private void btn_lampara4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara4ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara4ActionPerformed

    private void btn_lampara3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara3ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara3ActionPerformed

    private void btn_lampara10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampara10ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampara10ActionPerformed

    private void btn_lampar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lampar9ActionPerformed
        //JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador - 1) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, m);
        contador--;
        validar();
    }//GEN-LAST:event_btn_lampar9ActionPerformed

    private void btn_genioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_genioActionPerformed

        Icon w = new ImageIcon(getClass().getResource("/imagenes/pista2.gif"));
        btn_genio.setIcon(w);
        Genio ve = new Genio();
        ve.setVisible(true);
        Genio.setPrueba2(0);
 //boton1.setEnabled(false);

    }//GEN-LAST:event_btn_genioActionPerformed

    private void lbl_fondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_fondoMouseClicked

    private void btn_lampara3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lampara3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lampara3MouseClicked

    private void btn_lampara6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lampara6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lampara6MouseClicked

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed

        Historia.setPrueba1(0);       
        String strRespuesta = "";
        strRespuesta = (new Pregunta().preguntaConfirmacion("¿Estás seguro de regresar al menú principal?"));
        if ("SI".equals(strRespuesta)) {
            MenuPrincipal v = new MenuPrincipal();
            v.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PalabraSecreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PalabraSecreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PalabraSecreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PalabraSecreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PalabraSecreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_genio;
    private javax.swing.JButton btn_lampar9;
    private javax.swing.JButton btn_lampara;
    private javax.swing.JButton btn_lampara10;
    private javax.swing.JButton btn_lampara2;
    private javax.swing.JButton btn_lampara3;
    private javax.swing.JButton btn_lampara4;
    private javax.swing.JButton btn_lampara5;
    private javax.swing.JButton btn_lampara6;
    private javax.swing.JButton btn_lampara7;
    private javax.swing.JButton btn_lampara8;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables

    Icon m = new ImageIcon(getClass().getResource("/imagenes/0intentos.png"));
    Icon n = new ImageIcon(getClass().getResource("/imagenes/1intentos.png"));
    Icon d = new ImageIcon(getClass().getResource("/imagenes/2intentos.png"));
    Icon e = new ImageIcon(getClass().getResource("/imagenes/esqueleto.png"));

    public void validar() {
        switch (contador) {
            case 2:
                JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, d);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Oh no, haz elegido la lámpara equivocada. Tienes " + (contador) + " intentos", "ERROR", JOptionPane.CANCEL_OPTION, n);
                break;
            case 0:

                JOptionPane.showMessageDialog(null, ":( Se te han acabado los intentos, repetiremos el intro", "SIN INTENTOS", JOptionPane.CANCEL_OPTION, e);

                MenuPrincipal v = new MenuPrincipal();
                v.setVisible(true);
                this.dispose();
                contador = 3;
                Historia.setPrueba1(0);
                Genio.setPrueba2(0);
                break;
            default:
                break;
        }

    }

 

}
