/*
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : Perfil
//PROCESO : Configuración
//DESCRIPCION : El código nos indicará los daos del jugador
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class Perfil extends javax.swing.JFrame {

   

    public Perfil() {
        initComponents();

        setLocationRelativeTo(this);

        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

        btn_regresar.setOpaque(false);
        btn_regresar.setBorder(BorderFactory.createEmptyBorder());
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.setToolTipText("regresar");

        txt_nombre.setText(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getNombre());
        ImageIcon avatar1 = new ImageIcon(this.getClass().getResource(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getAvatar()));
        DecimalFormat formateador = new DecimalFormat("##.##");

       
        lbl_avatar1.setIcon(avatar1); // Enviando el avatar

        txt_ganadas.setText(String.valueOf(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getGanadas()));

        txt_jugadas.setText(String.valueOf(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getJugadas()));
        txt_perdidas.setText(String.valueOf(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getPerdidas()));

        String r = formateador.format(IniciarSesion.listaJugadores.get(IniciarSesion.posicion).getRecord());

        txt_record.setText(r + "%");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new jtextfieldround.JTextFieldRound();
        txt_jugadas = new jtextfieldround.JTextFieldRound();
        txt_ganadas = new jtextfieldround.JTextFieldRound();
        txt_perdidas = new jtextfieldround.JTextFieldRound();
        txt_record = new jtextfieldround.JTextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        lbl_avatar1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 16)); // NOI18N
        jLabel7.setText("Avatar Actual");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        txt_nombre.setEditable(false);
        txt_nombre.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, -1));

        txt_jugadas.setEditable(false);
        txt_jugadas.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        getContentPane().add(txt_jugadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 180, -1));

        txt_ganadas.setEditable(false);
        txt_ganadas.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        getContentPane().add(txt_ganadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 180, 30));

        txt_perdidas.setEditable(false);
        txt_perdidas.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        getContentPane().add(txt_perdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 180, -1));

        txt_record.setEditable(false);
        txt_record.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        getContentPane().add(txt_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 180, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel8.setText("Mayor Puntaje");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));
        getContentPane().add(lbl_avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 230, 230));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel6.setText("N° De Juegos Perdidos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel5.setText("N° Juegos Ganados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel4.setText("N° Veces Jugadas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel3.setText("Nombre :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perfil de Jugador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 970, -1));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoArabew.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        ConfiguracionGeneral con = new ConfiguracionGeneral();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel lbl_avatar1;
    private jtextfieldround.JTextFieldRound txt_ganadas;
    private jtextfieldround.JTextFieldRound txt_jugadas;
    private jtextfieldround.JTextFieldRound txt_nombre;
    private jtextfieldround.JTextFieldRound txt_perdidas;
    private jtextfieldround.JTextFieldRound txt_record;
    // End of variables declaration//GEN-END:variables
 

}
