/*
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : Registro
//PROCESO : Ingreso
//DESCRIPCION : El código esta validad para que el jugador ingrese sus datos para realizar el registro
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import Clases.Archivo;
import Clases.Jugador;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Registro extends javax.swing.JFrame {

    static String imagen = "";
    static double re = 0.0;
    static int contador = 3;
    static Archivo archivo = new Archivo();
    static Jugador jugador, lista[];

    public Registro() {
        initComponents();

        lbl_genio.setOpaque(false);
        lbl_genio.setBorder(BorderFactory.createEmptyBorder());
        lbl_genio.setToolTipText("genio");
        lbl_jazmin.setOpaque(false);
        lbl_jazmin.setBorder(BorderFactory.createEmptyBorder());
        lbl_jazmin.setToolTipText("jazmin");
        lbl_aladin.setOpaque(false);
        lbl_aladin.setBorder(BorderFactory.createEmptyBorder());
        lbl_aladin.setToolTipText("aladin");
         btn_regresar.setOpaque(false);
        btn_regresar.setBorder(BorderFactory.createEmptyBorder());
        btn_regresar.setContentAreaFilled(false);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_confirmarContrasena = new jtextfieldround.JPasswordFieldRound();
        btn_regresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_aladin = new javax.swing.JLabel();
        lbl_avatarOriginal = new javax.swing.JLabel();
        rbtn_avatar1 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_genio = new javax.swing.JLabel();
        rbtn_avatar2 = new javax.swing.JRadioButton();
        lbl_jazmin = new javax.swing.JLabel();
        rbtn_avatar3 = new javax.swing.JRadioButton();
        txt_nombre = new jtextfieldround.JTextFieldRound();
        txt_contrasena = new jtextfieldround.JPasswordFieldRound();
        txt_edad = new jtextfieldround.JTextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        btn_registrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_confirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 330, -1));

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 0, 17)); // NOI18N
        jLabel7.setText("Confirmar Contraseña (*):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 0, 17)); // NOI18N
        jLabel6.setText("Contraseña (*):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 0, 17)); // NOI18N
        jLabel4.setText("Edad (*):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 0, 17)); // NOI18N
        jLabel5.setText("Nombre de usuario (*):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, -1));

        lbl_aladin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aladdinoficial.png"))); // NOI18N
        getContentPane().add(lbl_aladin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 160, 160));

        lbl_avatarOriginal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/musulman.png"))); // NOI18N
        getContentPane().add(lbl_avatarOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 180, 170));

        rbtn_avatar1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        rbtn_avatar1.setText("Aladdin");
        rbtn_avatar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_avatar1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_avatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Escoge un avatar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 970, 40));

        lbl_genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/genioOficial.png"))); // NOI18N
        getContentPane().add(lbl_genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 150, 150));

        rbtn_avatar2.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        rbtn_avatar2.setText("Genio");
        rbtn_avatar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_avatar2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_avatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        lbl_jazmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jazminoficial.png"))); // NOI18N
        getContentPane().add(lbl_jazmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 180, -1));

        rbtn_avatar3.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        rbtn_avatar3.setText("Jazmine");
        rbtn_avatar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_avatar3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_avatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        txt_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nombre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        txt_nombre.setSelectionColor(new java.awt.Color(255, 255, 255));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 330, 30));
        getContentPane().add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 330, -1));

        txt_edad.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 330, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 970, -1));

        btn_registrarse.setFont(new java.awt.Font("Lucida Handwriting", 0, 16)); // NOI18N
        btn_registrarse.setText("Registrarse");
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoArabew.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INCIA SESION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 970, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        Icon q = new ImageIcon(getClass().getResource("/imagenes/0intentos.png"));
        Icon a = new ImageIcon(getClass().getResource("/imagenes/2intentos.png"));
        Icon w = new ImageIcon(getClass().getResource("/imagenes/feliz.png"));
        int limiteEdad = 2;
        int limiteCont = 8;

        Jugador njugador;
        String direccion = "C:/AliBabá/Jugadores.txt";
        Archivo archivito = new Archivo();
        String nom = txt_nombre.getText();
        String ed = txt_edad.getText();
        String c = txt_contrasena.getText();
        String avatar = imagen;

        njugador = new Jugador(nom, ed, c, 0, 0, 0, 0.0, avatar);

        try {
            if (txt_nombre.getText() == null || txt_nombre.getText().equals("") || txt_contrasena.getText() == null || txt_contrasena.getText().equals("") || txt_confirmarContrasena.getText() == null || txt_confirmarContrasena.getText().equals("") || this.txt_edad.getText() == null) {
                JOptionPane.showMessageDialog(null, "Asegúrate de llenar todos los campos", "ERROR", JOptionPane.CANCEL_OPTION, a);
                return;
            }

            if (!this.txt_edad.getText().matches("[0-9]*")) {
                JOptionPane.showMessageDialog(null, "El campo edad contiene solo números", "ERROR", JOptionPane.CANCEL_OPTION, a);
                return;
            }
            if (txt_edad.getText().length() > limiteEdad) {
                JOptionPane.showMessageDialog(null, "Oh no, ingresa tu edad correctamente", "ERROR", JOptionPane.CANCEL_OPTION, a);
                return;
            }

            if (txt_contrasena.getText().length() < limiteCont) {
                JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos 8 dígitos", "ERROR", JOptionPane.CANCEL_OPTION, a);
                return;
            }
            if (!txt_confirmarContrasena.getText().equals(txt_contrasena.getText())) {
                contador--;
                validar();
                return;
            }
        } catch (HeadlessException ev) {

        }

        if (archivito.archivoExiste(direccion)) {

            try {
                if (buscarJugador(nom) == false) {
                    archivito.guardar(njugador, direccion, IniciarSesion.listaJugadores);
                    JOptionPane.showMessageDialog(null, "Jugador Registrado con éxito", "", JOptionPane.CANCEL_OPTION, w);

                    IniciarSesion p = new IniciarSesion();
                    p.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe, intenta con otro", "INTENTA DE NUEVO", JOptionPane.CANCEL_OPTION, q);

                }

            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);

            }

        } else {
            File file = new File(direccion);
            try {
                archivito.guardar(njugador, direccion, IniciarSesion.listaJugadores);
                JOptionPane.showMessageDialog(null, "Jugador Registrado con éxito", "", JOptionPane.CANCEL_OPTION, w);

            } catch (IOException ex) {
                Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
            }
            IniciarSesion p = new IniciarSesion();
            p.setVisible(true);
            this.dispose();
        }
 

    }//GEN-LAST:event_btn_registrarseActionPerformed

    private void rbtn_avatar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_avatar1ActionPerformed
        if (rbtn_avatar1.isSelected()) {
            imagen = "/imagenes/aladdinoficial.png";
            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/aladdinoficial.png"));

            lbl_avatarOriginal.setIcon(dos);

            rbtn_avatar2.setSelected(false);
            rbtn_avatar3.setSelected(false);
        } else {

            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/musulman.png"));
            lbl_avatarOriginal.setIcon(dos);
        }

    }//GEN-LAST:event_rbtn_avatar1ActionPerformed

    private void rbtn_avatar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_avatar2ActionPerformed
        if (rbtn_avatar2.isSelected()) {
            imagen = "/imagenes/genioOficial.png";
            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/genioOficial.png"));
            lbl_avatarOriginal.setIcon(dos);
            rbtn_avatar1.setSelected(false);
            rbtn_avatar3.setSelected(false);
        } else {
            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/musulman.png"));
            lbl_avatarOriginal.setIcon(dos);

        }
    }//GEN-LAST:event_rbtn_avatar2ActionPerformed

    private void rbtn_avatar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_avatar3ActionPerformed
        if (rbtn_avatar3.isSelected()) {
            imagen = "/imagenes/jazminoficial.png";
            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/jazminoficial.png"));
            lbl_avatarOriginal.setIcon(dos);
            rbtn_avatar2.setSelected(false);
            rbtn_avatar1.setSelected(false);
        } else {
            ImageIcon dos = new ImageIcon(this.getClass().getResource("/imagenes/musulman.png"));
            lbl_avatarOriginal.setIcon(dos);

        }
    }//GEN-LAST:event_rbtn_avatar3ActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        IniciarSesion v = new IniciarSesion();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_aladin;
    private javax.swing.JLabel lbl_avatarOriginal;
    private javax.swing.JLabel lbl_genio;
    private javax.swing.JLabel lbl_jazmin;
    private javax.swing.JRadioButton rbtn_avatar1;
    private javax.swing.JRadioButton rbtn_avatar2;
    private javax.swing.JRadioButton rbtn_avatar3;
    private jtextfieldround.JPasswordFieldRound txt_confirmarContrasena;
    private jtextfieldround.JPasswordFieldRound txt_contrasena;
    private jtextfieldround.JTextFieldRound txt_edad;
    private jtextfieldround.JTextFieldRound txt_nombre;
    // End of variables declaration//GEN-END:variables
public static boolean buscarJugador(String nombre) throws IOException, FileNotFoundException, ClassNotFoundException {
        Jugador per = null;
        boolean existe = false;
        for (Jugador p : IniciarSesion.listaJugadores) {
            if (p.getNombre().equals(nombre)) {
                per = p;
                existe = true;
            }
        }

        return existe;
    }
    Icon m = new ImageIcon(getClass().getResource("/imagenes/0intentos.png"));
    Icon n = new ImageIcon(getClass().getResource("/imagenes/1intentos.png"));
    Icon d = new ImageIcon(getClass().getResource("/imagenes/2intentos.png"));
    Icon e = new ImageIcon(getClass().getResource("/imagenes/enojado.png"));

    public void validar() {
        switch (contador) {
            case 2:
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, tienes " + (contador) + " intentos", "Error", JOptionPane.CANCEL_OPTION, d);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, tienes " + (contador) + " intentos", "Error", JOptionPane.CANCEL_OPTION, n);
                break;
            case 0:

                JOptionPane.showMessageDialog(null, "Oh no! Intenta de nuevo", "SIN INTENTOS", JOptionPane.CANCEL_OPTION, e);

                txt_nombre.setText("");
                txt_edad.setText("");
                txt_contrasena.setText("");
                txt_confirmarContrasena.setText("");

                contador = 3;
                Historia.setPrueba1(0);
                Genio.setPrueba2(0);
                break;
            default:
                break;
        }

    }

}
