/*
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SISTEMA : ALIBABÁ Y LOS CIENTO UN MIL LADRONES
//MODULO : Configuracion
//PROCESO : Ingreso
//DESCRIPCION : El código esta validado para que el jugador acepte los terminos o condiciones o no
//ANALISTAS : Ing. Mauro Rosas
//PROGRAMADOR : Saúl Alpala, Doménica Erazo, Samantha Jara
//FECHA CREACION, MODIFICACION:23 de agosto 2020, 20 de septiembre 2020
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

 */
package Ventanas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class TerminosCondiciones extends javax.swing.JFrame {

    public TerminosCondiciones() {

        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        check_aceptar = new javax.swing.JCheckBox();
        check_noAceptar = new javax.swing.JCheckBox();
        btn_confirmar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea_terminos = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        check_aceptar.setText("Lo acepto, estoy de acuerdo con los términos y condiciones");
        check_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(check_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        check_noAceptar.setForeground(new java.awt.Color(255, 255, 255));
        check_noAceptar.setText("No estoy de acuerdo");
        check_noAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_noAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(check_noAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        btn_confirmar.setBackground(new java.awt.Color(255, 255, 255));
        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        txtarea_terminos.setEditable(false);
        txtarea_terminos.setColumns(20);
        txtarea_terminos.setRows(5);
        txtarea_terminos.setText("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\n\tTERMINOS Y CONDICIONES\n░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\nEl presente establece los términos en que AliBabá y \nlos ciento un mil ladrones usa y protege la \ninformación que es proporcionada por sus usuarios \nal momento de utilizar su sitio web. Este juego \nestá comprometido con la seguridad de los datos \nde sus usuarios. Cuando le pedimos llenar los \ncampos de información personal con la cual usted \npueda ser identificado, lo hacemos asegurando que\n sólo se empleará de acuerdo con los términos de \neste documento.\n\nUso de la información recogida\n\nNuestro juego emplea la información con el fin de\n proporcionar el mejor servicio posible, \nparticularmente para mantener un registro de \nusuarios, de pedidos en caso que aplique, y\n mejorar nuestros productos y servicios.  \nAliBabá y los ciento un mil ladrones está \naltamente comprometido para cumplir con el \ncompromiso de mantener su información segura. \nUsamos los sistemas más avanzados y los \nactualizamos constantemente para asegurarnos \nque no exista ningún acceso no autorizado.\n\nEsta compañía no venderá, cederá ni distribuirá \nla información personal que es recopilada sin su \nconsentimiento, salvo que sea requerido por un \njuez con un orden judicial.\n\nAliBabá y los ciento un mil ladrones Se reserva \nel derecho de cambiar los términos de la presente \nPolítica de Privacidad en cualquier momento\n");
        txtarea_terminos.setBorder(null);
        jScrollPane2.setViewportView(txtarea_terminos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 470, 330));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Por favor lea el acuerdo de licencia y seleccione ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terminos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 287, 484));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"acepto\" si está de acuerdo con los términos y condiciones.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondow.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_aceptarActionPerformed
        if (check_aceptar.isSelected()) {
            check_noAceptar.setSelected(false);
        }
    }//GEN-LAST:event_check_aceptarActionPerformed

    private void check_noAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_noAceptarActionPerformed
        if (check_noAceptar.isSelected()) {
            check_aceptar.setSelected(false);
        }
    }//GEN-LAST:event_check_noAceptarActionPerformed

    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        if (check_aceptar.isSelected()) {

            IniciarSesion ve = new IniciarSesion();
            ve.setVisible(true);

            this.dispose();
        } else if (check_noAceptar.isSelected()) {

            cancelar();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor elija una opción");
        }
    }//GEN-LAST:event_btn_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerminosCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerminosCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerminosCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerminosCondiciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerminosCondiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JCheckBox check_aceptar;
    private javax.swing.JCheckBox check_noAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtarea_terminos;
    // End of variables declaration//GEN-END:variables
private void cancelar() {
        if (JOptionPane.showConfirmDialog(rootPane, "Está seguro de cancelar la ejecución?", "Salir sitema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {

            this.dispose();

        } 
    }
}
